// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler_test

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// DeleteURL provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteURL(alias string) error {
	ret := _mock.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(alias)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_DeleteURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteURL'
type MockStorage_DeleteURL_Call struct {
	*mock.Call
}

// DeleteURL is a helper method to define mock.On call
//   - alias string
func (_e *MockStorage_Expecter) DeleteURL(alias interface{}) *MockStorage_DeleteURL_Call {
	return &MockStorage_DeleteURL_Call{Call: _e.mock.On("DeleteURL", alias)}
}

func (_c *MockStorage_DeleteURL_Call) Run(run func(alias string)) *MockStorage_DeleteURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteURL_Call) Return(err error) *MockStorage_DeleteURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_DeleteURL_Call) RunAndReturn(run func(alias string) error) *MockStorage_DeleteURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function for the type MockStorage
func (_mock *MockStorage) GetURL(alias string) (string, error) {
	ret := _mock.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(alias)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(alias)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(alias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockStorage_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - alias string
func (_e *MockStorage_Expecter) GetURL(alias interface{}) *MockStorage_GetURL_Call {
	return &MockStorage_GetURL_Call{Call: _e.mock.On("GetURL", alias)}
}

func (_c *MockStorage_GetURL_Call) Run(run func(alias string)) *MockStorage_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_GetURL_Call) Return(s string, err error) *MockStorage_GetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorage_GetURL_Call) RunAndReturn(run func(alias string) (string, error)) *MockStorage_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// SaveURL provides a mock function for the type MockStorage
func (_mock *MockStorage) SaveURL(url string, alias string) (int64, error) {
	ret := _mock.Called(url, alias)

	if len(ret) == 0 {
		panic("no return value specified for SaveURL")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (int64, error)); ok {
		return returnFunc(url, alias)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = returnFunc(url, alias)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(url, alias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_SaveURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveURL'
type MockStorage_SaveURL_Call struct {
	*mock.Call
}

// SaveURL is a helper method to define mock.On call
//   - url string
//   - alias string
func (_e *MockStorage_Expecter) SaveURL(url interface{}, alias interface{}) *MockStorage_SaveURL_Call {
	return &MockStorage_SaveURL_Call{Call: _e.mock.On("SaveURL", url, alias)}
}

func (_c *MockStorage_SaveURL_Call) Run(run func(url string, alias string)) *MockStorage_SaveURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_SaveURL_Call) Return(n int64, err error) *MockStorage_SaveURL_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorage_SaveURL_Call) RunAndReturn(run func(url string, alias string) (int64, error)) *MockStorage_SaveURL_Call {
	_c.Call.Return(run)
	return _c
}
